// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxRQPwvnfHOTekEQwDGIM-SSzIEGolUCA',
    appId: '1:1024166491765:web:15fd77398fdc9f831e2a3c',
    messagingSenderId: '1024166491765',
    projectId: 'swiperight-40d18',
    authDomain: 'swiperight-40d18.firebaseapp.com',
    storageBucket: 'swiperight-40d18.appspot.com',
    measurementId: 'G-5D8Z2M1M9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbhJnaCKIqxX5JPIW91_veEPl3GhsEXTI',
    appId: '1:1024166491765:android:4a558c251afebcf21e2a3c',
    messagingSenderId: '1024166491765',
    projectId: 'swiperight-40d18',
    storageBucket: 'swiperight-40d18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpyEPV0KkxrJBr3-tAG_qEqe8IHSkk1Rs',
    appId: '1:1024166491765:ios:a504992de740680d1e2a3c',
    messagingSenderId: '1024166491765',
    projectId: 'swiperight-40d18',
    storageBucket: 'swiperight-40d18.appspot.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpyEPV0KkxrJBr3-tAG_qEqe8IHSkk1Rs',
    appId: '1:1024166491765:ios:e8be20ca48f2693a1e2a3c',
    messagingSenderId: '1024166491765',
    projectId: 'swiperight-40d18',
    storageBucket: 'swiperight-40d18.appspot.com',
    iosBundleId: 'com.example.untitled4.RunnerTests',
  );
}
